# Generated by Django 5.2.6 on 2025-11-01 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harbor_mgmt', '0002_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
