# Generated by Django 5.2.6 on 2025-11-19 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harbor_mgmt', '0003_userprofile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='reserved_until',
            field=models.DateTimeField(blank=True, help_text='If reserved, booking is held until this datetime.', null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reserved', 'Reserved'), ('expired', 'Expired'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
