# Generated by Django 5.2.6 on 2025-11-19 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harbor_mgmt', '0004_booking_reserved_until_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='details',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
