# Generated by Django 5.2.6 on 2025-12-02 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harbor_mgmt', '0005_booking_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_reference',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
